- name: Play One -- ansible_call_by_url
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create Azure deployment in Resource Group(No Need to Created Above)
    azure_rm_deployment:
      state: present
      resource_group_name: "jenkins-azure"
      name: "jenkins-azure"
      location: "eastus"
      template_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/master/jenkins-cicd-container/azuredeploy.json'
      parameters_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/master/jenkins-cicd-container/azuredeploy.parameters.json'
