- name: Play One -- Create Azure VM
  hosts: localhost
  vars:
    resource_group_name: "ansible_master"
    vm_name: "myvm-{{ dpVersion }}"
    location: japaneast
    vm_user: chenkiegcp2
    deployment_name: "myDeployment-{{ dpVersion }}"
    authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC69c3Z6HTUJ1ywmCoTGJuRVQwrw6NzWmeI3A37pvJLvFXOmkcQR0ILgY0b07F78mn0EgXYIjkjbBMIRS3IRlhd1JTWdsaG+vh3W7UCpBQ74VED29sxrLwcGZDlI5zmtVR0J4h9qjbf1TBWWPoEaj6QHeuM1T5tbfXW/wjE0OLMHzfxk2f4EuUZEllFaiCHI/wstxuYwXJNn4Fa7xod9hQgLdFEsU1cg98r/ujVu4dUwR5MvIjWC+O+IlHW5/QoUiw5Hr6vvKrVsp4nrEb7ofVdk8nA8Gai9KPG2PgpVXnw7lcYICBYSQQMFA9xrT/ESNXTUSPPqEZld4R5Bw2VCI2p
  connection: local
  gather_facts: false
  become: yes
  tasks:
  - name: Create Azure deployment in Resource Group(No Need to Created Above)
    azure_rm_deployment:
      state: present
      resource_group_name: "{{ resource_group_name }}"
      name: "{{ deployment_name }}"
      location: "{{ location }}"
      template_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/master/101-vm-simple-rhel-unmanaged/azuredeploy.json'
      parameters:
        vmName:
          value: "{{ vm_name }}"
        adminUsername:
          value: "{{ vm_user }}"
        adminPasswordOrKey:
          value: "{{ authorized_key }}"
    register: azure

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item['ips'][0].public_ip }}"
      groupname: azure_vms
    loop: "{{ azure.deployment.instances }}"
# Play Two
# ===========
# Setup VM
- name: Setup VM -- Play Two
  hosts: azure_vms
  user: chenkiegcp2
  become: yes
  gather_facts: false
  tasks:
  - name: install python3
    package:
      name:
        - git
        - python3
        - python3-pip
      state: latest
  - name: Method RPM - Add Microsoft repository GPG key.
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Method RPM - Add Microsoft repo for Azure CLI
    yum_repository:
      name: azure-cli
      description: Microsoft Azure CLI
      baseurl: https://packages.microsoft.com/yumrepos/azure-cli
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
      gpgcheck: yes
  - name: Method RPM - Install Azure CLI (az)
    package:
      name: "azure-cli"
      state: latest
      
  - name: pip install ansbile
    shell: pip3 install ansible --user
    register: result
    become: false
