- name: Play One -- Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create Azure deployment in Resource Group(No Need to Created Above)
    azure_rm_deployment:
      state: present
      resource_group_name: "uvw"
      name: "uvw"
      location: "japaneast"
      template_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/master/101-vm-simple-rhel-unmanaged/azuredeploy.json'
      parameters_link: 'https://raw.githubusercontent.com/NKStupid/azure-quickstart-templates/master/101-vm-simple-rhel-unmanaged/azuredeploy.parameters.json'
    register: azure

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item['ips'][0].public_ip }}"
      groupname: azure_vms
    loop: "{{ azure.deployment.instances }}"
# Play Two
# ===========
# Configure Azure VM
- name: Configure Azure VM -- Play Two
  hosts: azure_vms
  gather_facts: false
  user: chenkiegcp2
  become: yes
  tasks:
  - name: Wait for SSH to come up
    wait_for:
      port: 22
      timeout: 2000
      state: started
  - name: echo the hostname of the vm
    shell: hostname

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    unarchive:
      src: https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
  - name: /etc/yum.repos.d/jenkins.repo 
    get_url:
      url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
  - name: Example action to import a key from a url
    rpm_key:
      state: present
      key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key
  - name: install git openjdk and jenkins
    package:
      name:
        - java-1.8.0-openjdk
        - git
        - jenkins
      state: latest
  - name: JAVA_HOME and M2_HOME
    get_url:
      url: https://raw.githubusercontent.com/NKStupid/Tools/master/create-ansible-lab/.bash_profile
      dest: ~/
  - name: source .bash_profile of JAVA_HOME and M2_HOME
    action: shell source ~/.bash_profile
  - name: start jenkins
    service:
      name: jenkins
      enabled: true
      state: started
  - name: start firewalld services
    service:
      name: firewalld
      enabled: true
      state: started
  - name: open firewalld 80
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
  - name: open firewalld 8080
    firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled
      immediate: yes
